export const Colors = {
    // light:{
    //     listItem: 'blue',
    //     inputTextColor: 'black',
    //     inputBgColor: 'lightblue',
    //     backgroundColor: 'wheat',
    //     totalTasks: 'red',
    //     completedTasks: 'green',
    //     addBtn: 'red',
    //     editBtn: 'green',
    //     deleteBtn: 'red',
    // },
    // dark:{
    //     listItem: 'black',
    //     inputTextColor: 'white',
    //     inputBgColor: 'rgba(0, 0, 0, .3)',
    //     backgroundColor: 'grey',
    //     totalTasks: 'black',
    //     completedTasks: 'brown',
    //     addBtn: 'black',
    //     editBtn: 'brown',
    //     deleteBtn: 'black',
    // },
    dark:{
        listItem: 'blue',
        inputTextColor: 'black',
        inputBgColor: 'lightblue',
        backgroundColor: 'wheat',
        totalTasks: 'red',
        completedTasks: 'green',
        addBtn: 'red',
        editBtn: 'green',
        deleteBtn: 'red',
    },
    light:{
        listItem: 'blue',
        inputTextColor: 'black',
        inputBgColor: 'lightblue',
        backgroundColor: 'wheat',
        totalTasks: 'red',
        completedTasks: 'green',
        addBtn: 'red',
        editBtn: 'green',
        deleteBtn: 'red',
    }
}